replicaCount: 1

image:
  repository: your-registry/kubernetes-claude-mcp
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}
podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 80
  # For NodePort
  nodePort: null

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}
tolerations: []
affinity: {}

livenessProbe:
  httpGet:
    path: /api/v1/health
    port: 8080
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /api/v1/health
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 10

config:
  server:
    address: ":8080"
    readTimeout: 30
    writeTimeout: 60
  kubernetes:
    inCluster: true
    defaultNamespace: "default"
  argocd:
    url: "https://argocd.example.com"
    insecure: false
  gitlab:
    url: "https://gitlab.com"
    apiVersion: "v4"
  claude:
    baseURL: "https://api.anthropic.com"
    modelID: "claude-3-7-sonnet-20250219"
    maxTokens: 4096
    temperature: 0.7

secrets:
  # Set these values in a separate values file or via --set flag
  claude:
    apiKey: ""
  argocd:
    authToken: ""
    # Or use username/password
    username: ""
    password: ""
  gitlab:
    authToken: ""

# Existing secrets (if you manage secrets outside Helm)
existingSecrets:
  claude:
    name: ""
    key: ""
  argocd:
    name: ""
    key: ""
  gitlab:
    name: ""
    key: ""