{{- if .Values.secrets.claude.apiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubernetes-claude-mcp.fullname" . }}-claude
  labels:
    {{- include "kubernetes-claude-mcp.labels" . | nindent 4 }}
type: Opaque
stringData:
  api-key: {{ .Values.secrets.claude.apiKey | quote }}
{{- end }}
---
{{- if or .Values.secrets.argocd.authToken .Values.secrets.argocd.username .Values.secrets.argocd.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubernetes-claude-mcp.fullname" . }}-argocd
  labels:
    {{- include "kubernetes-claude-mcp.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.secrets.argocd.authToken }}
  auth-token: {{ .Values.secrets.argocd.authToken | quote }}
  {{- end }}
  {{- if .Values.secrets.argocd.username }}
  username: {{ .Values.secrets.argocd.username | quote }}
  {{- end }}
  {{- if .Values.secrets.argocd.password }}
  password: {{ .Values.secrets.argocd.password | quote }}
  {{- end }}
{{- end }}
---
{{- if .Values.secrets.gitlab.authToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubernetes-claude-mcp.fullname" . }}-gitlab
  labels:
    {{- include "kubernetes-claude-mcp.labels" . | nindent 4 }}
type: Opaque
stringData:
  auth-token: {{ .Values.secrets.gitlab.authToken | quote }}
{{- end }}